### ISSUE TITLE
Opera does not play nice

### ISSUE THREAD

**Issue by coldes** [FaroeMedia/scrollator#5]
Hello  - just been testing this plugin with great optimism as default scrollbars imho are just pointless and particularly with IE just plain ugly  - ALL was looking good this end however Opera 29 [WIN] does not seem to like this plugin - was looking for a "cross-the-board" browsers solution. Can you check your end

thank you

**Comment by ingipingi** [comment]
I've checked it here on Opera 29,  and it seems to work fine. What exactly doesn't work?

**Comment by coldes** [comment]
...apologies, was testing on MAC [trackpad] / Parallels Desktop / Windows 10 Tech Prev

Tried on a Windows Laptop and all good

**Comment by jogvana** [comment]
Thanks for getting back. We'll close the the case then. Hope the plugin will be of great help for you.
