### ISSUE TITLE
Making work with "SmoothScroll.js"

### ISSUE THREAD

**Issue by federone** [FaroeMedia/scrollator#6]
hi,

thank you very much for script,

is there any way to make it work with "SmoothScroll.js"? - https://github.com/galambalazs/smoothscroll-for-websites - when loading your scrollbar, smoothscroll dont works ...

best regards,
Federico

**Comment by jogvana** [comment]
Hi Federico.

Thanks alot for your request. We'll get back to you asap.

Kind regards
Jógvan

**Comment by federone** [comment]
hi,

is there any news?

thank you so much,
Federico

**Comment by jogvana** [comment]
It does not seem as we have a quick fix for this. Hopefully we can look further at this later. Sorry for the inconvenience and please let us know if there are any further questions.
